apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: anmol-dhama/order-service:latest
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: myapp
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
