apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: anmol-dhama/payment-service:latest
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: myapp
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: ClusterIP
